FROM golang:1.9
RUN apt-get update && apt-get install -y libtool libltdl-dev vim
RUN mkdir -p ${GOPATH}/src/github.com/hyperledger && \
	cd ${GOPATH}/src/github.com/hyperledger/ && \
	git clone https://github.com/hyperledger/fabric.git && \
	git clone https://github.com/hyperledger/fabric-samples.git && \
	cd ${GOPATH}/src/github.com/hyperledger/fabric && \
	git checkout tags/v1.0.5  && \
	cd ${GOPATH}/src/github.com/hyperledger/fabric/common/tools/cryptogen && \
	go build && \
	mv cryptogen /usr/bin/cryptogen && \
	cd ${GOPATH}/src/github.com/hyperledger/fabric/common/configtx/tool/configtxgen && \
	go build && \
	mv configtxgen /usr/bin/configtxgen
#	rm -rf ${GOPATH}/src/github.com/hyperledger

# Install docker CLI
RUN wget https://get.docker.com/builds/Linux/x86_64/docker-17.05.0-ce.tgz
RUN tar -xvf docker-17.05.0-ce.tgz
RUN cp docker/docker /usr/sbin/docker

ADD fabric_utils /utils
RUN cp /utils/*.sh /usr/bin/ && \
    touch /utils/core.yaml && \
    cp /usr/bin/cryptogen /utils/cryptogen && \
    cp /usr/bin/configtxgen /utils/configtxgen

ADD ./output/executable/peer /usr/bin/peer

RUN chmod 755 /utils/*.sh

ENV FABRIC_CFG_PATH=/utils

WORKDIR /utils
